[package]
name = "integer"
version = "0.1.0"
authors = ["Trevor Barker <tmbarker9@gmail.com>"]
repository = "https://github.com/tmbarker/project-euler"
workspace = "../.."
edition = "2021"

[dependencies]
num-integer = "0.1.46"
num-traits = "0.2.19"
